#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2021 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

include:
  - template: Terraform.gitlab-ci.yml

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/0.15:v0.12.0

stages:
  - init
  - validate
  - build
  - deploy
  - deploy infrastructure
  - deploy app
  - cleanup

before_script:
  - if [ ${CI_COMMIT_REF_NAME} == master ];
    then source environments/.production.env;
    else source environments/.testing.env;
    fi

variables:
  TF_ROOT: terraform

# disable the pre-defined deploy job
deploy:
  extends: .deploy
  dependencies:
    - build
  only:
    - never

deploy staging environment:
  stage: deploy infrastructure
  extends: .deploy
  dependencies:
    - build
  when: on_success
  allow_failure: false
  only:
    - branches
    - tags
  except:
    - master

deploy production environment:
  stage: deploy infrastructure
  extends: .deploy
  dependencies:
    - build
  only:
    - master

cleanup:
  extends: .destroy
  only:
    - branches
    - tags
  except:
    - master