include:
  - template: Terraform.latest.gitlab-ci.yml

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/0.15:v0.12.0

stages:
  - init
  - validate
  - build
  - deploy
  - deploy infrastructure
  - deploy app
  - cleanup

before_script:
  - if [ ${CI_COMMIT_REF_NAME} == master ];
    then source environments/.master.env;
    else source environments/.testing.env;
    fi

variables:
  TF_ROOT: terraform

# disable the pre-defined deploy job
deploy:
  extends: .deploy
  dependencies:
    - build
  only:
    - never

deploy staging environment:
  stage: deploy infrastructure
  extends: .deploy
  dependencies:
    - build
  when: on_success
  allow_failure: false
  only:
    - branches
    - tags
  except:
    - master

deploy production environment:
  stage: deploy infrastructure
  extends: .deploy
  dependencies:
    - build
  only:
    - master

deploy app:
  stage: deploy app
  trigger:
    project: weathernetwork/app
    branch: master
  only:
    - master

cleanup:
  extends: .destroy
  only:
    - branches
    - tags
  except:
    - master